LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY instruction_decode IS
    PORT (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        IR : IN STD_LOGIC_VECTOR(31 DOWNTO 0); -- instruction from IF/ID.IR
        NPC : IN STD_LOGIC_VECTOR(31 DOWNTO 0); -- next PC from IF/ID.NPC
        -- gets register values passed in now (from register_file.vhd)
        A_in : IN STD_LOGIC_VECTOR(31 DOWNTO 0) := (OTHERS => '0');
        B_in : IN STD_LOGIC_VECTOR(31 DOWNTO 0) := (OTHERS => '0');

        A : OUT STD_LOGIC_VECTOR(31 DOWNTO 0); -- register operand A = Regs[rs1]
        B : OUT STD_LOGIC_VECTOR(31 DOWNTO 0); -- register operand B = Regs[rs2]
        Imm : OUT STD_LOGIC_VECTOR(31 DOWNTO 0); -- sign-extended immediate
        IR_out : OUT STD_LOGIC_VECTOR(31 DOWNTO 0); -- pass-through instruction
        NPC_out : OUT STD_LOGIC_VECTOR(31 DOWNTO 0); -- pass-through NPC

        -- control signals generated by decode
        ALUSrc : OUT STD_LOGIC; -- 0: ALU uses register operand B, 1: ALU uses immediate imm
        ALUOp : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
        ALUFunc : OUT STD_LOGIC_VECTOR(3 DOWNTO 0); -- exact ALU operation select for EX stage
        Branch : OUT STD_LOGIC; --Do we branch or not
        BranchType : OUT STD_LOGIC_VECTOR(2 DOWNTO 0); --Branch type (000 : equal, 001: not equal, 100: less than, 101: greater thn or equal)
        Jump : OUT STD_LOGIC; --If we jump or not  
        JumpReg : OUT STD_LOGIC; --If we jump to an instruction who's address is in a register
        MemRead : OUT STD_LOGIC; --If we read data memory
        MemWrite : OUT STD_LOGIC; --If we write to data memory
        RegWrite : OUT STD_LOGIC; --Wether the instruction write to a DST register
        MemToReg : OUT STD_LOGIC --If a we load data from memory into a register
    );
END instruction_decode;

ARCHITECTURE rtl OF instruction_decode IS
    -- extracted instruction fields
    SIGNAL opcode : STD_LOGIC_VECTOR(6 DOWNTO 0);
    SIGNAL funct3 : STD_LOGIC_VECTOR(2 DOWNTO 0);
    SIGNAL funct7 : STD_LOGIC_VECTOR(6 DOWNTO 0);
    SIGNAL imm_i : STD_LOGIC_VECTOR(31 DOWNTO 0);
    SIGNAL imm_s : STD_LOGIC_VECTOR(31 DOWNTO 0);
    SIGNAL imm_b : STD_LOGIC_VECTOR(31 DOWNTO 0);
    SIGNAL imm_u : STD_LOGIC_VECTOR(31 DOWNTO 0);
    SIGNAL imm_j : STD_LOGIC_VECTOR(31 DOWNTO 0);
BEGIN
    -- combinatorial field extraction
    opcode <= IR(6 DOWNTO 0);
    funct3 <= IR(14 DOWNTO 12);
    funct7 <= IR(31 DOWNTO 25);

    -- immediate generation by RV32I format
    imm_i <= STD_LOGIC_VECTOR(resize(signed(IR(31 DOWNTO 20)), 32));
    imm_s <= STD_LOGIC_VECTOR(resize(signed(IR(31 DOWNTO 25) & IR(11 DOWNTO 7)), 32));
    imm_b <= STD_LOGIC_VECTOR(resize(signed(IR(31) & IR(7) & IR(30 DOWNTO 25) & IR(11 DOWNTO 8) & '0'), 32));
    imm_u <= IR(31 DOWNTO 12) & "000000000000";
    imm_j <= STD_LOGIC_VECTOR(resize(signed(IR(31) & IR(19 DOWNTO 12) & IR(20) & IR(30 DOWNTO 21) & '0'), 32));

    -- register file reads and pass-through values
    A <= A_in;
    B <= B_in;
    IR_out <= IR;
    NPC_out <= NPC;

    -- immediate selection based on opcode/format
    PROCESS (opcode, imm_i, imm_s, imm_b, imm_u, imm_j)
    BEGIN
        Imm <= (OTHERS => '0');

        CASE opcode IS
            WHEN "0010011" | "0000011" | "1100111" => -- I-type (ALU-immediate, loads, jalr)
                Imm <= imm_i;

            WHEN "0100011" => -- S-type (stores)
                Imm <= imm_s;

            WHEN "1100011" => -- B-type (branches)
                Imm <= imm_b;

            WHEN "0110111" | "0010111" => -- U-type (lui, auipc)
                Imm <= imm_u;

            WHEN "1101111" => -- J-type (jal)
                Imm <= imm_j;

            WHEN OTHERS =>
                NULL;
        END CASE;
    END PROCESS;

    -- combinatorial control signal generation based on opcode
    PROCESS (opcode, funct3, funct7)
    BEGIN
        -- default control values
        ALUSrc <= '0';
        ALUOp <= "00";
        ALUFunc <= "0000";
        Branch <= '0';
        BranchType <= (OTHERS => '0');
        Jump <= '0';
        JumpReg <= '0';
        MemRead <= '0';
        MemWrite <= '0';
        RegWrite <= '0';
        MemToReg <= '0';

        -- instructions: add, sub, mul, or, and, addi, xori, ori, andi, lw, sw, beq, bne, blt, bge, jal, jalr, lui, sll, srl, sra, slti, auipc

        CASE opcode IS
            WHEN "0110011" => -- R-type ALU
                ALUSrc <= '0';
                ALUOp <= "10";
                RegWrite <= '1';
                -- R-type supported: add, sub, mul, or, and, sll, srl, sra
                CASE funct3 IS
                    WHEN "000" =>
                        IF funct7 = "0000000" THEN -- add
                            ALUFunc <= "0000";
                        ELSIF funct7 = "0100000" THEN -- sub
                            ALUFunc <= "0001";
                        ELSIF funct7 = "0000001" THEN -- mul ...this should be from the RV32M extension from the googling I did
                            ALUFunc <= "0010";
                        ELSE
                            RegWrite <= '0';
                        END IF;

                    WHEN "110" => -- or
                        IF funct7 = "0000000" THEN
                            ALUFunc <= "0100";
                        ELSE
                            RegWrite <= '0';
                        END IF;

                    WHEN "111" => -- and
                        IF funct7 = "0000000" THEN
                            ALUFunc <= "0011";
                        ELSE
                            RegWrite <= '0';
                        END IF;

                    WHEN "001" => -- sll
                        IF funct7 = "0000000" THEN
                            ALUFunc <= "0101";
                        ELSE
                            RegWrite <= '0';
                        END IF;

                    WHEN "101" =>
                        IF funct7 = "0000000" THEN -- srl
                            ALUFunc <= "0110";
                        ELSIF funct7 = "0100000" THEN -- sra
                            ALUFunc <= "0111";
                        ELSE
                            RegWrite <= '0';
                        END IF;

                    WHEN OTHERS =>
                        RegWrite <= '0';
                END CASE;

            WHEN "0010011" => -- I-type ALU (addi, xori, ori, andi, slti)
                ALUSrc <= '1';
                ALUOp <= "10";
                RegWrite <= '1';
                CASE funct3 IS
                    WHEN "000" => ALUFunc <= "0000"; -- addi
                    WHEN "100" => ALUFunc <= "1000"; -- xori
                    WHEN "110" => ALUFunc <= "0100"; -- ori
                    WHEN "111" => ALUFunc <= "0011"; -- andi
                    WHEN "010" => ALUFunc <= "1001"; -- slti
                    WHEN OTHERS =>
                        RegWrite <= '0';
                END CASE;

            WHEN "0000011" => -- loads (required: lw)
                IF funct3 = "010" THEN
                    ALUSrc <= '1';
                    ALUOp <= "00";
                    ALUFunc <= "0000"; -- base + offset address calc
                    MemRead <= '1';
                    RegWrite <= '1';
                    MemToReg <= '1';
                END IF;

            WHEN "0100011" => -- stores (required: sw)
                IF funct3 = "010" THEN
                    ALUSrc <= '1';
                    ALUOp <= "00";
                    ALUFunc <= "0000"; -- base + offset address calc
                    MemWrite <= '1';
                END IF;

            WHEN "1100011" => -- branches (required: beq, bne, blt, bge)
                IF (funct3 = "000") OR (funct3 = "001") OR (funct3 = "100") OR (funct3 = "101") THEN
                    ALUSrc <= '0';
                    ALUOp <= "01";
                    Branch <= '1';
                    BranchType <= funct3;
                END IF;

            WHEN "1101111" => -- jal
                ALUSrc <= '1';
                ALUOp <= "00";
                ALUFunc <= "0000";
                RegWrite <= '1';
                Jump <= '1';

            WHEN "1100111" => -- jalr
                ALUSrc <= '1';
                ALUOp <= "00";
                ALUFunc <= "0000";
                RegWrite <= '1';
                JumpReg <= '1';

            WHEN "0110111" => -- lui
                ALUSrc <= '1';
                ALUOp <= "11";
                ALUFunc <= "1010";
                RegWrite <= '1';

            WHEN "0010111" => -- auipc
                ALUSrc <= '1';
                ALUOp <= "00";
                ALUFunc <= "0000";
                RegWrite <= '1';

            WHEN OTHERS =>
                NULL;
        END CASE;
    END PROCESS;
END rtl;