LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity instruction_decode is
    port(
        clk : in STD_LOGIC;
        reset : in STD_LOGIC;
        IR : in STD_LOGIC_VECTOR(31 DOWNTO 0);					-- instruction from IF/ID.IR
        NPC : in STD_LOGIC_VECTOR(31 DOWNTO 0);				-- next PC from IF/ID.NPC
        -- gets register values passed in now (from register_dile.vhd)
        A_in : in STD_LOGIC_VECTOR(31 DOWNTO 0) := (others => '0');
        B_in : in STD_LOGIC_VECTOR(31 DOWNTO 0) := (others => '0');

        A : out STD_LOGIC_VECTOR(31 DOWNTO 0);					-- register operand A = Regs[rs1]
        B : out STD_LOGIC_VECTOR(31 DOWNTO 0);					-- register operand B = Regs[rs2]
        Imm : out STD_LOGIC_VECTOR(31 DOWNTO 0);				-- sign-extended immediate
        IR_out : out STD_LOGIC_VECTOR(31 DOWNTO 0);			-- pass-through instruction
        NPC_out : out STD_LOGIC_VECTOR(31 DOWNTO 0);			-- pass-through NPC

        -- control signals generated by decode
        ALUSrc : out STD_LOGIC; -- 0: ALU uses register operand B, 1: ALU uses immediate imm
        ALUOp : out STD_LOGIC_VECTOR(1 DOWNTO 0);
        ALUFunc : out STD_LOGIC_VECTOR(3 DOWNTO 0); -- exact ALU operation select for EX stage
        Branch : out STD_LOGIC;
        BranchType : out STD_LOGIC_VECTOR(2 DOWNTO 0);
        Jump : out STD_LOGIC;
        JumpReg : out STD_LOGIC;
        MemRead : out STD_LOGIC;
        MemWrite : out STD_LOGIC;
        RegWrite : out STD_LOGIC;
        MemToReg : out STD_LOGIC
    );
end instruction_decode;

architecture rtl of instruction_decode is
    -- extracted instruction fields
    signal opcode : STD_LOGIC_VECTOR(6 DOWNTO 0);
    signal funct3 : STD_LOGIC_VECTOR(2 DOWNTO 0);
    signal funct7 : STD_LOGIC_VECTOR(6 DOWNTO 0);
    signal imm_i : STD_LOGIC_VECTOR(31 DOWNTO 0);
    signal imm_s : STD_LOGIC_VECTOR(31 DOWNTO 0);
    signal imm_b : STD_LOGIC_VECTOR(31 DOWNTO 0);
    signal imm_u : STD_LOGIC_VECTOR(31 DOWNTO 0);
    signal imm_j : STD_LOGIC_VECTOR(31 DOWNTO 0);
begin
    -- combinatorial field extraction
    opcode <= IR(6 DOWNTO 0);
    funct3 <= IR(14 DOWNTO 12);
    funct7 <= IR(31 DOWNTO 25);

    -- immediate generation by RV32I format
    -- !! not sure if im doing the extension properly... sign extend vs zero extend?
    imm_i <= std_logic_vector(resize(signed(IR(31 DOWNTO 20)), 32));
    imm_s <= std_logic_vector(resize(signed(IR(31 DOWNTO 25) & IR(11 DOWNTO 7)), 32));
    imm_b <= std_logic_vector(resize(signed(IR(31) & IR(7) & IR(30 DOWNTO 25) & IR(11 DOWNTO 8) & '0'), 32));
    imm_u <= IR(31 DOWNTO 12) & "000000000000";
    imm_j <= std_logic_vector(resize(signed(IR(31) & IR(19 DOWNTO 12) & IR(20) & IR(30 DOWNTO 21) & '0'), 32));

    -- register file reads and pass-through values
    A <= A_in;
    B <= B_in;
    IR_out <= IR;
    NPC_out <= NPC;

    -- immediate selection based on opcode/format
    process(opcode, imm_i, imm_s, imm_b, imm_u, imm_j)
    begin
        Imm <= (others => '0');

        case opcode is
            when "0010011" | "0000011" | "1100111" =>	-- I-type (ALU-immediate, loads, jalr)
                Imm <= imm_i;

            when "0100011" =>								-- S-type (stores)
                Imm <= imm_s;

            when "1100011" =>								-- B-type (branches)
                Imm <= imm_b;

            when "0110111" | "0010111" =>				-- U-type (lui, auipc)
                Imm <= imm_u;

            when "1101111" =>								-- J-type (jal)
                Imm <= imm_j;

            when others =>
                null;
        end case;
    end process;

    -- combinatorial control signal generation based on opcode
    process(opcode, funct3, funct7)
    begin
        -- default control values
        ALUSrc <= '0';
        ALUOp <= "00";
        ALUFunc <= "0000";
        Branch <= '0';
        BranchType <= (others => '0');
        Jump <= '0';
        JumpReg <= '0';
        MemRead <= '0';
        MemWrite <= '0';
        RegWrite <= '0';
        MemToReg <= '0';

        -- instructions: add, sub, mul, or, and, addi, xori, ori, andi, lw, sw, beq, bne, blt, bge, jal, jalr, lui, sll, srl, sra, slti, auipc

        case opcode is
            when "0110011" =>						-- R-type ALU
                ALUSrc <= '0';
                ALUOp <= "10";
                RegWrite <= '1';
                -- R-type supported: add, sub, mul, or, and, sll, srl, sra
                case funct3 is
                    when "000" =>
                        if funct7 = "0000000" then		-- add
                            ALUFunc <= "0000";
                        elsif funct7 = "0100000" then	-- sub
                            ALUFunc <= "0001";
                        elsif funct7 = "0000001" then	-- mul ...this should be from the RV32M extension from the googling I did
                            ALUFunc <= "0010";
                        else
                            RegWrite <= '0';
                        end if;

                    when "110" =>						-- or
                        if funct7 = "0000000" then
                            ALUFunc <= "0100";
                        else
                            RegWrite <= '0';
                        end if;

                    when "111" =>						-- and
                        if funct7 = "0000000" then
                            ALUFunc <= "0011";
                        else
                            RegWrite <= '0';
                        end if;

                    when "001" =>						-- sll
                        if funct7 = "0000000" then
                            ALUFunc <= "0101";
                        else
                            RegWrite <= '0';
                        end if;

                    when "101" =>
                        if funct7 = "0000000" then		-- srl
                            ALUFunc <= "0110";
                        elsif funct7 = "0100000" then	-- sra
                            ALUFunc <= "0111";
                        else
                            RegWrite <= '0';
                        end if;

                    when others =>
                        RegWrite <= '0';
                end case;

            when "0010011" =>						-- I-type ALU (addi, xori, ori, andi, slti)
                ALUSrc <= '1';
                ALUOp <= "10";
                RegWrite <= '1';
                case funct3 is
                    when "000" => ALUFunc <= "0000";	-- addi
                    when "100" => ALUFunc <= "1000";	-- xori
                    when "110" => ALUFunc <= "0100";	-- ori
                    when "111" => ALUFunc <= "0011";	-- andi
                    when "010" => ALUFunc <= "1001";	-- slti
                    when others =>
                        RegWrite <= '0';
                end case;

            when "0000011" =>						-- loads (required: lw)
                if funct3 = "010" then
                    ALUSrc <= '1';
                    ALUOp <= "00";
                    ALUFunc <= "0000";				-- base + offset address calc
                    MemRead <= '1';
                    RegWrite <= '1';
                    MemToReg <= '1';
                end if;

            when "0100011" =>						-- stores (required: sw)
                if funct3 = "010" then
                    ALUSrc <= '1';
                    ALUOp <= "00";
                    ALUFunc <= "0000";				-- base + offset address calc
                    MemWrite <= '1';
                end if;

            when "1100011" =>						-- branches (required: beq, bne, blt, bge)
                if (funct3 = "000") or (funct3 = "001") or (funct3 = "100") or (funct3 = "101") then
                    ALUSrc <= '0';
                    ALUOp <= "01";
                    Branch <= '1';
                    BranchType <= funct3;
                end if;

            when "1101111" =>						-- jal
                ALUSrc <= '1';
                ALUOp <= "00";
                ALUFunc <= "0000";
                RegWrite <= '1';
				Jump <= '1';

            when "1100111" =>						-- jalr
                ALUSrc <= '1';
                ALUOp <= "00";
                ALUFunc <= "0000";
                RegWrite <= '1';
				JumpReg <= '1';

            when "0110111" =>						-- lui
                ALUSrc <= '1';
                ALUOp <= "11";
                ALUFunc <= "1010";
                RegWrite <= '1';

            when "0010111" =>						-- auipc
                ALUSrc <= '1';
                ALUOp <= "00";
                ALUFunc <= "0000";
                RegWrite <= '1';

            when others =>
                null;
        end case;
    end process;
end rtl;